#cloud-config
runcmd:
  - rpm --import https://repo.saltproject.io/salt/py3/redhat/8/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
  - curl -fsSL https://repo.saltproject.io/salt/py3/redhat/8/x86_64/latest.repo | tee /etc/yum.repos.d/salt.repo
  - dnf install git salt-master salt-minion -y
  - cd /root/ && git clone https://github.com/SergSha/lab-11.git
  - cp -rf /root/lab-11/srv/salt /srv/
  - cp -f /root/lab-11/etc/salt/master.d/file_roots.conf /etc/salt/master.d/
  - systemctl enable --now salt-master salt-minion
  - sleep 60
  - salt-key -a 'jump-*' -y
  - salt-key -a 'backend-*' -y
  - salt-key -a 'nginx-*' -y
