#cloud-config
runcmd:
  - sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/8/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
  - curl -fsSL https://repo.saltproject.io/salt/py3/redhat/8/x86_64/latest.repo | sudo tee /etc/yum.repos.d/salt.repo
  - sudo dnf install salt-master salt-minion -y
#users:
#  - name: cloud-user
#    groups: sudo
#    shell: /bin/bash
#    sudo: 'ALL=(ALL) NOPASSWD:ALL'
#    ssh-authorized-keys:
#      - <содержимое_SSH-ключа>
