#cloud-config
runcmd:
  - rpm --import https://repo.saltproject.io/salt/py3/redhat/8/x86_64/SALTSTACK-GPG-KEY.pub
  - curl -fsSL https://repo.saltproject.io/salt/py3/redhat/8/x86_64/3006.repo | tee /etc/yum.repos.d/salt.repo
  - dnf install git salt-master salt-minion -y
  - cd /root/ && git clone https://github.com/SergSha/lab-11.git
  - cp -rf /root/lab-11/srv/{salt,pillar} /srv/
  - cp -f /root/lab-11/etc/salt/master.d/{file_roots,pillar}.conf /etc/salt/master.d/
  - systemctl enable --now salt-master salt-minion
  - sleep 90
  - salt-key -a 'jump-*' -y
  - salt-key -a 'db-*' -y
  - salt-key -a 'backend-*' -y
  - salt-key -a 'nginx-*' -y
